.PHONY: all
all: first second third
	@echo "\$$@ = $@"
	@echo "$$^ = $^"
	@echo "$$< = $<"
first:
	@echo "1 first"
# @echo "first \$$@ = $@"
# @echo "first $$^ = $^"
# @echo "first $$< = $<"
second:
	@echo "2 second"	
third:
	@echo "3 third"

	